extern const GeoLayout thi_fan_geo[];
extern Lights1 thi_fan_f3dlite_material_lights;
extern u8 thi_fan__0_ci8[];
extern u8 thi_fan__0_pal_rgba16[];
extern Vtx thi_fan_000_displaylist_mesh_layer_1_vtx_0[132];
extern Gfx thi_fan_000_displaylist_mesh_layer_1_tri_0[];
extern Gfx mat_thi_fan_f3dlite_material[];
extern Gfx mat_revert_thi_fan_f3dlite_material[];
extern Gfx thi_fan_000_displaylist_mesh_layer_1[];
extern Gfx thi_fan_material_revert_render_settings[];
