extern const GeoLayout sa_static_flower_geo[];
extern Lights1 sa_static_flower_Material_0_f3d_lights;
extern Lights1 sa_static_flower_Material_1_f3d_lights;
extern u8 sa_static_flower__0_rgba16[];
extern u8 sa_static_flower__1_rgba16[];
extern Vtx sa_static_flower_000_displaylist_mesh_layer_1_vtx_0[46];
extern Gfx sa_static_flower_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx sa_static_flower_000_displaylist_mesh_layer_1_vtx_1[41];
extern Gfx sa_static_flower_000_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_sa_static_flower_Material_0_f3d[];
extern Gfx mat_revert_sa_static_flower_Material_0_f3d[];
extern Gfx mat_sa_static_flower_Material_1_f3d[];
extern Gfx sa_static_flower_000_displaylist_mesh_layer_1[];
