extern const GeoLayout hmc_gear_geo[];
extern Lights1 hmc_gear_f3dlite_material_lights;
extern u8 hmc_gear__0_ci4[];
extern u8 hmc_gear__0_pal_rgba16[];
extern Vtx hmc_gear_sm64_mesh_mesh_layer_1_vtx_0[152];
extern Gfx hmc_gear_sm64_mesh_mesh_layer_1_tri_0[];
extern Gfx mat_hmc_gear_f3dlite_material[];
extern Gfx mat_revert_hmc_gear_f3dlite_material[];
extern Gfx hmc_gear_sm64_mesh_mesh_layer_1[];
extern Gfx hmc_gear_material_revert_render_settings[];
