extern const GeoLayout sl_static_tree_geo[];
extern Lights1 sl_static_tree_Material_0_f3d_001_lights;
extern Lights1 sl_static_tree_Material_1_f3d_001_lights;
extern u8 sl_static_tree__0_rgba16[];
extern u8 sl_static_tree__1_rgba16[];
extern Vtx sl_static_tree_000_displaylist_mesh_layer_4_vtx_0[251];
extern Gfx sl_static_tree_000_displaylist_mesh_layer_4_tri_0[];
extern Vtx sl_static_tree_000_displaylist_mesh_layer_1_vtx_0[39];
extern Gfx sl_static_tree_000_displaylist_mesh_layer_1_tri_0[];
extern Gfx mat_sl_static_tree_Material_0_f3d_001[];
extern Gfx mat_revert_sl_static_tree_Material_0_f3d_001[];
extern Gfx mat_sl_static_tree_Material_1_f3d_001[];
extern Gfx sl_static_tree_000_displaylist_mesh_layer_4[];
extern Gfx sl_static_tree_000_displaylist_mesh_layer_1[];
extern Gfx sl_static_tree_material_revert_render_settings[];
