extern const GeoLayout nep_enut_000_switch_opt1[];
extern const GeoLayout nep_enut_000_switch_opt2[];
extern const GeoLayout nep_enut_002_switch_opt1[];
extern const GeoLayout nep_enut_002_switch_opt2[];
extern const GeoLayout nep_enut_geo[];
extern Lights1 nep_enut_Material_0_f3d_lights;
extern Lights1 nep_enut_Fast3D_Material_003_lights;
extern Lights1 nep_enut_Material_1_f3d_lights;
extern Lights1 nep_enut_Fast3D_Material_002_lights;
extern u8 nep_enut__0_rgba16[];
extern u8 nep_enut__0_i8[];
extern u8 nep_enut__1_rgba16[];
extern u8 nep_enut__3_rgba16[];
extern Vtx nep_enut_000_displaylist_mesh_layer_1_vtx_0[64];
extern Gfx nep_enut_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx nep_enut_000_displaylist_001_mesh_layer_1_vtx_0[60];
extern Gfx nep_enut_000_displaylist_001_mesh_layer_1_tri_0[];
extern Vtx nep_enut_000_displaylist_001_mesh_layer_1_vtx_1[14];
extern Gfx nep_enut_000_displaylist_001_mesh_layer_1_tri_1[];
extern Vtx nep_enut_000_displaylist_001_mesh_layer_1_vtx_2[439];
extern Gfx nep_enut_000_displaylist_001_mesh_layer_1_tri_2[];
extern Vtx nep_enut_004_offset_mesh_layer_4_vtx_0[4];
extern Gfx nep_enut_004_offset_mesh_layer_4_tri_0[];
extern Vtx nep_enut_005_offset_mesh_layer_4_vtx_0[4];
extern Gfx nep_enut_005_offset_mesh_layer_4_tri_0[];
extern Gfx mat_nep_enut_Material_0_f3d[];
extern Gfx mat_nep_enut_Fast3D_Material_003[];
extern Gfx mat_nep_enut_Material_1_f3d[];
extern Gfx mat_nep_enut_Fast3D_Material_002[];
extern Gfx mat_nep_enut_Material_3_f3d[];
extern Gfx mat_revert_nep_enut_Material_3_f3d[];
extern Gfx nep_enut_000_displaylist_mesh_layer_1[];
extern Gfx nep_enut_000_displaylist_mesh_layer_1_mat_override_Material_0_f3d_0[];
extern Gfx nep_enut_000_displaylist_mesh_layer_1_mat_override_Fast3D_Material_003_1[];
extern Gfx nep_enut_000_displaylist_001_mesh_layer_1[];
extern Gfx nep_enut_000_displaylist_001_mesh_layer_1_mat_override_Material_0_f3d_0[];
extern Gfx nep_enut_000_displaylist_001_mesh_layer_1_mat_override_Fast3D_Material_003_1[];
extern Gfx nep_enut_004_offset_mesh_layer_4[];
extern Gfx nep_enut_005_offset_mesh_layer_4[];
