#include "levels/castle_grounds/texture_include.inc.c"
#include "levels/castle_grounds/area_1/collision.inc.c"
#include "levels/castle_grounds/area_1/macro.inc.c"
#include "levels/castle_grounds/area_1/spline.inc.c"
#include "levels/castle_grounds/area_2/collision.inc.c"
#include "levels/castle_grounds/area_2/macro.inc.c"
#include "levels/castle_grounds/area_2/spline.inc.c"
#include "levels/castle_grounds/model.inc.c"
