#ifndef SA_HEADER_H
#define SA_HEADER_H
#include "types.h"
#include "game/moving_texture.h"
extern const LevelScript level_sa_entry[];
extern const LevelScript local_area_sa_1_[];
extern const LevelScript local_objects_sa_1_[];
extern const LevelScript local_warps_sa_1_[];
extern const LevelScript local_area_sa_2_[];
extern const LevelScript local_objects_sa_2_[];
extern const LevelScript local_warps_sa_2_[];
extern const LevelScript local_area_sa_3_[];
extern const LevelScript local_objects_sa_3_[];
extern const LevelScript local_warps_sa_3_[];
extern const GeoLayout Geo_sa_1_0x2801700[];
extern Gfx DL_sa_1_0xe046bc0[];
extern Gfx DL_sa_1_0xe05a970[];
extern Gfx DL_sa_1_0xe05d550[];
extern Gfx DL_sa_1_0x700c9d0[];
extern const Collision col_sa_1_0xe054e50[];
extern const LevelScript level_sa_entry[];
extern const LevelScript local_area_sa_1_[];
extern const LevelScript local_objects_sa_1_[];
extern const LevelScript local_warps_sa_1_[];
extern const LevelScript local_area_sa_2_[];
extern const LevelScript local_objects_sa_2_[];
extern const LevelScript local_warps_sa_2_[];
extern const LevelScript local_area_sa_3_[];
extern const LevelScript local_objects_sa_3_[];
extern const LevelScript local_warps_sa_3_[];
extern const GeoLayout Geo_sa_2_0x2801600[];
extern Gfx DL_sa_2_0xe0a1d48[];
extern Gfx DL_sa_2_0xe0aa5d0[];
extern Gfx DL_sa_2_0x70222a0[];
extern const Collision col_sa_2_0xe0a9380[];
extern const LevelScript level_sa_entry[];
extern const LevelScript local_area_sa_1_[];
extern const LevelScript local_objects_sa_1_[];
extern const LevelScript local_warps_sa_1_[];
extern const LevelScript local_area_sa_2_[];
extern const LevelScript local_objects_sa_2_[];
extern const LevelScript local_warps_sa_2_[];
extern const LevelScript local_area_sa_3_[];
extern const LevelScript local_objects_sa_3_[];
extern const LevelScript local_warps_sa_3_[];
extern const GeoLayout Geo_sa_3_0x2801500[];
extern Gfx DL_sa_3_0xe0e8500[];
extern Gfx DL_sa_3_0xe0f71f0[];
extern const Collision col_sa_3_0xe0f0c68[];
extern const LevelScript level_sa_entry[];
extern const LevelScript local_area_sa_1_[];
extern const LevelScript local_objects_sa_1_[];
extern const LevelScript local_warps_sa_1_[];
extern const LevelScript local_area_sa_2_[];
extern const LevelScript local_objects_sa_2_[];
extern const LevelScript local_warps_sa_2_[];
extern const LevelScript local_area_sa_3_[];
extern const LevelScript local_objects_sa_3_[];
extern const LevelScript local_warps_sa_3_[];
extern const LevelScript level_sa_entry[];
extern const GeoLayout sa_geo_000170[];
extern const Gfx sa_seg7_dl_07002DE8[];
extern const Gfx sa_seg7_dl_07002FD0[];
extern const Collision sa_seg7_collision[];
extern const MacroObject sa_seg7_macro_objs[];
extern const LevelScript level_sa_entry[];
#endif