extern const GeoLayout cloud_flower_geo[];
extern Lights1 cloud_flower_Material_0_f3d_lights;
extern Lights1 cloud_flower_Material_1_f3d_lights;
extern Lights1 cloud_flower_Material_2_f3d_lights;
extern u8 cloud_flower__0_rgba16[];
extern u8 cloud_flower__1_rgba16[];
extern u8 cloud_flower__2_rgba16[];
extern Vtx cloud_flower_000_displaylist_mesh_layer_1_vtx_0[10];
extern Gfx cloud_flower_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx cloud_flower_000_displaylist_mesh_layer_1_vtx_1[184];
extern Gfx cloud_flower_000_displaylist_mesh_layer_1_tri_1[];
extern Vtx cloud_flower_000_displaylist_mesh_layer_1_vtx_2[11];
extern Gfx cloud_flower_000_displaylist_mesh_layer_1_tri_2[];
extern Gfx mat_cloud_flower_Material_0_f3d[];
extern Gfx mat_cloud_flower_Material_1_f3d[];
extern Gfx mat_cloud_flower_Material_2_f3d[];
extern Gfx cloud_flower_000_displaylist_mesh_layer_1[];
extern Gfx cloud_flower_material_revert_render_settings[];
