extern const GeoLayout rocket_door_geo[];
extern Lights1 rocket_door_Material_0_f3d_lights;
extern Lights1 rocket_door_Material_1_f3d_lights;
extern Lights1 rocket_door_Material_2_f3d_lights;
extern u8 rocket_door__0_rgba16[];
extern u8 rocket_door__1_rgba16[];
extern u8 rocket_door__2_rgba16[];
extern Vtx rocket_door_Bone_mesh_layer_1_vtx_0[6];
extern Gfx rocket_door_Bone_mesh_layer_1_tri_0[];
extern Vtx rocket_door_Bone_mesh_layer_1_vtx_1[4];
extern Gfx rocket_door_Bone_mesh_layer_1_tri_1[];
extern Vtx rocket_door_Bone_mesh_layer_1_vtx_2[62];
extern Gfx rocket_door_Bone_mesh_layer_1_tri_2[];
extern Gfx mat_rocket_door_Material_0_f3d[];
extern Gfx mat_rocket_door_Material_1_f3d[];
extern Gfx mat_rocket_door_Material_2_f3d[];
extern Gfx rocket_door_Bone_mesh_layer_1[];
