extern const GeoLayout bitfs_slime_geo[];
extern Lights1 bitfs_slime_f3dlite_material_lights;
extern u8 bitfs_slime__0_ci4[];
extern u8 bitfs_slime__0_pal_rgba16[];
extern Vtx bitfs_slime_000_displaylist_mesh_layer_5_vtx_0[22];
extern Gfx bitfs_slime_000_displaylist_mesh_layer_5_tri_0[];
extern Gfx mat_bitfs_slime_f3dlite_material[];
extern Gfx mat_revert_bitfs_slime_f3dlite_material[];
extern Gfx bitfs_slime_000_displaylist_mesh_layer_5[];
extern Gfx bitfs_slime_material_revert_render_settings[];
