extern const GeoLayout hmc_spike_geo[];
extern Lights1 hmc_spike_f3dlite_material_lights;
extern u8 hmc_spike__0_ci4[];
extern u8 hmc_spike__0_pal_rgba16[];
extern Vtx hmc_spike_000_displaylist_mesh_layer_1_vtx_0[320];
extern Gfx hmc_spike_000_displaylist_mesh_layer_1_tri_0[];
extern Gfx mat_hmc_spike_f3dlite_material[];
extern Gfx mat_revert_hmc_spike_f3dlite_material[];
extern Gfx hmc_spike_000_displaylist_mesh_layer_1[];
extern Gfx hmc_spike_material_revert_render_settings[];
