extern const GeoLayout green_floating_bubble_geo[];
extern Lights1 green_floating_bubble_Fast3D_Material_lights;
extern u8 green_floating_bubble__0_rgba16[];
extern Vtx green_floating_bubble_000_displaylist_mesh_layer_1_vtx_0[29];
extern Gfx green_floating_bubble_000_displaylist_mesh_layer_1_tri_0[];
extern Gfx mat_green_floating_bubble_Fast3D_Material[];
extern Gfx green_floating_bubble_000_displaylist_mesh_layer_1[];
