extern const GeoLayout star_hexagon_000_switch_opt1[];
extern const GeoLayout star_hexagon_geo[];
extern Lights1 star_hexagon_Material_0_f3d_lights;
extern Lights1 star_hexagon_Fast3D_Material_lights;
extern u8 star_hexagon__0_rgba16[];
extern Vtx star_hexagon_000_displaylist_mesh_layer_1_vtx_0[25];
extern Gfx star_hexagon_000_displaylist_mesh_layer_1_tri_0[];
extern Gfx mat_star_hexagon_Material_0_f3d[];
extern Gfx mat_star_hexagon_Fast3D_Material[];
extern Gfx star_hexagon_000_displaylist_mesh_layer_1[];
extern Gfx star_hexagon_000_displaylist_mesh_layer_1_mat_override_Fast3D_Material_0[];
