extern const GeoLayout pss_cloudy_platform_geo[];
extern Lights1 pss_cloudy_platform_f3dlite_material_001_lights;
extern u8 pss_cloudy_platform__0_ci8[];
extern u8 pss_cloudy_platform__0_pal_rgba16[];
extern Vtx pss_cloudy_platform_000_displaylist_mesh_layer_1_vtx_0[12];
extern Gfx pss_cloudy_platform_000_displaylist_mesh_layer_1_tri_0[];
extern Gfx mat_pss_cloudy_platform_f3dlite_material_001[];
extern Gfx mat_revert_pss_cloudy_platform_f3dlite_material_001[];
extern Gfx pss_cloudy_platform_000_displaylist_mesh_layer_1[];
