#ifndef JRB_HEADER_H
#define JRB_HEADER_H
#include "types.h"
#include "game/moving_texture.h"
extern const GeoLayout Geo_jrb_1_0x1d01700[];
extern Gfx DL_jrb_1_0xe0917a0[];
extern Gfx DL_jrb_1_0xe0baef0[];
extern Gfx DL_jrb_1_0x7002e10[];
extern const Collision col_jrb_1_0xe0a8ec0[];
extern struct MovtexQuadCollection jrb_1_Movtex_0[];
extern const GeoLayout Geo_jrb_2_0x1d01600[];
extern Gfx DL_jrb_2_0xe0cf340[];
extern const Collision col_jrb_2_0xe0d2b08[];
extern const GeoLayout Geo_jrb_3_0x1d01500[];
extern Gfx DL_jrb_3_0xe0ddc70[];
extern Gfx DL_jrb_3_0xe0e1210[];
extern const Collision col_jrb_3_0xe0e13d0[];
extern const LevelScript level_jrb_custom_entry[];
extern const LevelScript local_area_jrb_1_[];
extern const LevelScript local_objects_jrb_1_[];
extern const LevelScript local_warps_jrb_1_[];
extern const LevelScript local_area_jrb_2_[];
extern const LevelScript local_objects_jrb_2_[];
extern const LevelScript local_warps_jrb_2_[];
extern const LevelScript local_area_jrb_3_[];
extern const LevelScript local_objects_jrb_3_[];
extern const LevelScript local_warps_jrb_3_[];
extern const LevelScript level_jrb_entry[];
extern const GeoLayout jrb_geo_000900[];
extern const GeoLayout jrb_geo_000918[];
extern const GeoLayout jrb_geo_000930[];
extern const GeoLayout jrb_geo_000948[];
extern const GeoLayout jrb_geo_000960[];
extern const GeoLayout jrb_geo_000978[];
extern const GeoLayout jrb_geo_000990[];
extern const GeoLayout jrb_geo_0009B0[];
extern const GeoLayout jrb_geo_0009C8[];
extern const GeoLayout jrb_geo_0009E8[];
extern const GeoLayout jrb_geo_000A00[];
extern const GeoLayout jrb_geo_000A18[];
extern const GeoLayout jrb_geo_000AFC[];
extern const Gfx jrb_seg7_dl_07002FD0[];
extern const Gfx jrb_seg7_dl_07004940[];
extern const Gfx jrb_seg7_dl_07004C78[];
extern const Gfx jrb_seg7_dl_070058C8[];
extern const Gfx jrb_seg7_dl_070069B0[];
extern const Gfx jrb_seg7_dl_07007570[];
extern const Gfx jrb_seg7_dl_07007718[];
extern const Gfx jrb_seg7_dl_07007AC8[];
extern const Gfx jrb_seg7_dl_07007DC8[];
extern const Gfx jrb_seg7_dl_070080F8[];
extern const Gfx jrb_seg7_dl_07008FD8[];
extern const Gfx jrb_seg7_dl_070090B0[];
extern const Gfx jrb_seg7_dl_07009A58[];
extern const Gfx jrb_seg7_dl_07009B30[];
extern const Gfx jrb_seg7_dl_0700A608[];
extern const Gfx jrb_seg7_dl_0700AC68[];
extern const Gfx jrb_seg7_dl_0700AE48[];
extern const Gfx jrb_seg7_dl_0700AFB0[];
extern const Collision jrb_seg7_area_1_collision[];
extern const MacroObject jrb_seg7_area_1_macro_objs[];
extern const Collision jrb_seg7_collision_rock_solid[];
extern const Collision jrb_seg7_collision_floating_platform[];
extern const Collision jrb_seg7_collision_floating_box[];
extern const Collision jrb_seg7_collision_in_sunken_ship_3[];
extern const Collision jrb_seg7_collision_in_sunken_ship[];
extern const Collision jrb_seg7_collision_0700CEF0[];
extern const Collision jrb_seg7_collision_in_sunken_ship_2[];
extern const Collision jrb_seg7_collision_pillar_base[];
extern const Collision jrb_seg7_collision_0700D1DC[];
extern const Trajectory jrb_seg7_trajectory_unagi_1[];
extern const Trajectory jrb_seg7_trajectory_unagi_2[];
extern const struct MovtexQuadCollection jrb_movtex_water[];
extern const struct MovtexQuadCollection jrb_movtex_intial_mist[];
extern const Gfx jrb_seg7_dl_0700EF00[];
extern const Gfx jrb_seg7_dl_0700FE48[];
extern const Gfx jrb_seg7_dl_07010548[];
extern const Collision jrb_seg7_area_2_collision[];
extern const MacroObject jrb_seg7_area_2_macro_objs[];
extern const struct MovtexQuadCollection jrb_movtex_sinked_boat_water[];
extern const LevelScript level_jrb_entry[];
#endif