extern const GeoLayout goomba_bros_triangle_geo[];
extern Lights1 goomba_bros_triangle_f3dlite_material_007_lights;
extern u8 goomba_bros_triangle__0E0F4210_rgba16[];
extern Vtx goomba_bros_triangle_000_displaylist_mesh_layer_1_vtx_0[12];
extern Gfx goomba_bros_triangle_000_displaylist_mesh_layer_1_tri_0[];
extern Gfx mat_goomba_bros_triangle_f3dlite_material_007[];
extern Gfx goomba_bros_triangle_000_displaylist_mesh_layer_1[];
extern Gfx goomba_bros_triangle_material_revert_render_settings[];
