local dummy = setmetatable({}, {
    __index = function(_, _)
        return 0
    end
})

CUTSCENE_FLAG_SHOW_HUD = 0x04
CUTSCENE_FLAG_SKIPABLE = 0x08
CUTSCENE_FLAG_UNSKIPABLE = 0x10
CUTSCENE_FLAG_GREYOUT = 0x20
CUTSCENE_FLAG_SHAKE = 0x40
CUTSCENE_FLAG_END = 0x80

-- custom flags!
CUTSCENE_FLAG_KEEP_MUSIC = 0x100
CUTSCENE_FLAG_NEXT_CREDITS_ENTRY = 0x200