import re
from collections import defaultdict
from pathlib import Path

CUTSCENES = Path("./cutscenes")
OUT_FILE = Path("../cutscene-data.lua")
MAPPINGS_FILE = Path("./cutscene-mappings.lua")

COURSES = set([
    "BOB", "WF", "JRB", "CCM", "BBH",
    "HMC", "LLL", "SSL", "DDD", "SL",
    "WDW", "TTM", "THI", "TTC", "RR",
])

ACT_RE = re.compile(r"^CUTSCENE_([A-Z0-9]+)_ACT_(\d+)$")

def bytes_to_lua_str(data: bytes) -> str:
    return '"' + "".join(f"\\x{b:02x}" for b in data) + '"'

# returns CUTSCENE_BOB from CUTSCENE_BOB_ACT_1 etc
def course_prefix(varname: str) -> str:
    parts = varname.split("_", 2)
    return "_".join(parts[:2]) if len(parts) >= 2 else varname

def main():
    if not CUTSCENES.is_dir():
        raise FileNotFoundError(f"Directory not found: {CUTSCENES}")

    bin_files = sorted(CUTSCENES.glob("*.bin"))

    if not bin_files:
        print("No .bin files found.")
        return

    cutscene_data: dict[str, str] = {}
    star_cs: dict[str, dict[int, str]] = defaultdict(dict)

    for filepath in bin_files:
        varname = filepath.stem.upper()
        data = filepath.read_bytes()
        cutscene_data[varname] = bytes_to_lua_str(data)

        m = ACT_RE.match(varname)

        if m:
            course, act = m.group(1), int(m.group(2))
            if course in COURSES:
                star_cs[course][act] = varname

    lines = [
        "-- AUTOGENERATED by gen_cutscene_data.py do not edit!! --",
        "",
    ]

    prev_prefix = None
    
    for varname, lua_str in cutscene_data.items():
        prefix = course_prefix(varname)

        if prev_prefix is not None and prefix != prev_prefix:
            lines.append("")

        lines.append(f"{varname} = {lua_str}")
        prev_prefix = prefix

    lines += ["", "", "gStarCutscenes = {"]

    for course in COURSES:
        acts = star_cs.get(course, {})

        if not acts:
            lines.append(f"\t[COURSE_{course}] = {{}},")
        else:
            lines.append(f"\t[COURSE_{course}] = {{")

            for act in sorted(acts):
                lines.append(f"\t\t[{act}] = {acts[act]},")

            lines.append("\t},")

    lines += ["}", ""]

    if MAPPINGS_FILE.is_file():
        lines.append("")
        lines.append(MAPPINGS_FILE.read_text(encoding="utf-8").rstrip())

    OUT_FILE.write_text("\n".join(lines), encoding="utf-8")

    total_acts = sum(len(a) for a in star_cs.values())
    print(f"Written {OUT_FILE}  ({len(cutscene_data)} cutscenes, {total_acts} star cutscenes)")

if __name__ == "__main__":
    main()